# Nombre de la base de datos en memoria (H2)
spring.datasource.url=jdbc:h2:file:./data/jobtracker
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Le decimos a Hibernate (el motor que traduce Java <-> SQL) que cree/actualice
# las tablas automáticamente según nuestras Entidades. Muy útil en desarrollo.
spring.jpa.hibernate.ddl-auto=update

# Muestra por consola el SQL que se ejecuta, para que veas qué está pasando por dentro
spring.jpa.show-sql=true

# Habilita la consola web de H2, para poder ver la base de datos desde el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console